export const quizActionTypes = {
    FETCH_QUIZES_START: 'FETCH_QUIZES_START',
    FETCH_QUIZES_SUCCESS: 'FETCH_QUIZES_SUCCESS',
    FETCH_QUIZES_FAILURE: 'FETCH_QUIZES_FAILURE',
    ADD_OPTIONS: 'ADD_OPTIONS'
}   