export const quizActionTypes = {
    FETCH_QUIZES_START: 'FETCH_QUIZES_START',
    FETCH_QUIZES_SUCCESS: 'FETCH_QUIZES_SUCCESS',
    FETCH_QUIZES_FAILURE: 'FETCH_QUIZES_FAILURE',
    ADD_OPTIONS: 'ADD_OPTIONS',
    NEXT_QUESTION: 'NEXT_QUESTION',
    PREV_QUESTION: 'PREV_QUESTION',
}   