export const quizActionTypes = {
	FETCH_QUIZES_START: 'FETCH_QUIZES_START',
	FETCH_QUIZES_SUCCESS: 'FETCH_QUIZES_SUCCESS',
	FETCH_QUIZES_FAILURE: 'FETCH_QUIZES_FAILURE',
	ADD_OPTIONS: 'ADD_OPTIONS',
	NEXT_QUESTION: 'NEXT_QUESTION',
	PREV_QUESTION: 'PREV_QUESTION',
	SELECTED_ANSWER: 'SELECTED_ANSWER',
	SUBMIT_QUIZ: 'SUBMIT_QUIZ',
	RESET_ALL: 'RESET_ALL'
};
